site_name: 'Fab:UNIverse'

site_description: 'Fab:UNIverse ist eine Community und eine Tagung für diejenigen, die im deutschsprachigen Raum an Hochschulen Fab Labs, Makerspaces, offene Werkstätten und ähnliche Orte betreiben oder betreiben wollen.'

repo_url: https://github.com/fabuniverse/website
repo_name: Quellcode auf GitHub
edit_uri: https://github.com/fabuniverse/website/edit/main/docs/

theme: 
  name: material
  language: de
  icon:
    logo: 'fontawesome/solid/users-gear'
    edit: material/pencil 
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'Rubik'    
  features:
    - toc.follow
    - navigation.top
    - navigation.instant    
    - search.suggest 
    - search.highlight
    - navigation.tracking      
    - announce.dismiss
    - content.action.edit

nav:
    - Was ist Fab:UNIverse?: 'index.md'
    - 2024 - To Be Announced: '2024.md'
    - 2023 - Essen: '2023.md'
    - 2022 - Halle: '2022.md'
    - 2021 - Luckenwalde/hybrid: '2021.md'
    - 2020 - Stuttgart/hybrid: '2020.md'
    - 2019 - Berlin: '2019.md'
    - 2018 - Siegen: '2018.md'
    - 2017 - Wildau: '2017.md'
#    - Regionalgruppen: 'regional.md'
    - Zu Fab:UNIverse beitragen: 'beitragen.md'
    - Links: 'links.md'
    - Kontakt: 'kontakt.md'
    - Forum (intern): 'https://discourse.fab-universe.de'

markdown_extensions:
  - meta
  - toc:
  #    permalink: true
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences   
  - pymdownx.critic    
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - footnotes
  - attr_list

plugins:
  - search
  - glightbox

extra_css:
  - 'stylesheets/extra.css'

